version: '3.9'

services:
  postgres:
    container_name: screen_match_database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=screen_match
